# Generated by Django 3.2.12 on 2022-07-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderPhoneNo', models.CharField(max_length=11)),
                ('receiverPhoneNo', models.CharField(max_length=11)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNo',
            field=models.CharField(default=12, max_length=11),
            preserve_default=False,
        ),
    ]
